apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: dev-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: example@mail.com
    privateKeySecretRef:
      name: dev-prod
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
