include:
  - dataspace-compose.yaml

volumes:
  consumer-db:

networks:
  consumer-network:
    name: consumer-network

services:
  consumer-edc:
    image: ghcr.io/imec-int/edc-extensions/sovity-xce:latest
    platform: linux/amd64
    depends_on:
      consumer-db:
        condition: service_healthy
    environment:
      MY_EDC_PARTICIPANT_ID: 'consumer'
      MY_EDC_TITLE: 'Consumer EDC'
      MY_EDC_DESCRIPTION: 'Extended Sovity Community Edition EDC Connector'
      MY_EDC_CURATOR_URL: 'https://www.imec-int.com/en'
      MY_EDC_CURATOR_NAME: 'imec'
      MY_EDC_MAINTAINER_URL: 'https://www.imec-int.com/en'
      MY_EDC_MAINTAINER_NAME: 'imec'

      MY_EDC_FQDN: 'consumer-edc'
      EDC_API_AUTH_KEY: 'ApiKeyDefaultValue'

      WEB_HTTP_PUBLIC_PATH: '/public'
      WEB_HTTP_PUBLIC_PORT: 12001

      MY_EDC_JDBC_URL: 'jdbc:postgresql://consumer-db:5432/edc'
      MY_EDC_JDBC_USER: 'edc'
      MY_EDC_JDBC_PASSWORD: 'edc'

      # docker compose local dev environment overrides (don't use with non-dev images)
      MY_EDC_PROTOCOL: 'http://'
      EDC_DATAPLANE_TOKEN_VALIDATION_ENDPOINT: 'http://consumer-edc:11003/api/control/token'
      EDC_DSP_CALLBACK_ADDRESS: 'http://consumer-edc:11003/api/dsp'
      EDC_WEB_REST_CORS_ENABLED: 'true'
      EDC_WEB_REST_CORS_HEADERS: 'origin,content-type,accept,authorization,X-Api-Key'
      EDC_WEB_REST_CORS_ORIGINS: '*'
      EDC_AGENT_IDENTITY_KEY: 'client_id'

      # DAPS
      EDC_OAUTH_TOKEN_URL: 'http://daps:8080/realms/DAPS/protocol/openid-connect/token'
      EDC_OAUTH_PROVIDER_AUDIENCE: 'http://localhost:8080/realms/DAPS'
      EDC_OAUTH_PROVIDER_JWKS_URL: 'http://daps:8080/realms/DAPS/protocol/openid-connect/certs'
      EDC_OAUTH_TOKEN_EXPIRATION: 15 # in minutes
      EDC_OAUTH_CLIENT_ID: 'consumer'
      EDC_KEYSTORE: 'config/keystore/consumer.p12'
      EDC_KEYSTORE_PASSWORD: 'consumer'
      EDC_OAUTH_CERTIFICATE_ALIAS: 'consumer'
      EDC_OAUTH_PRIVATE_KEY_ALIAS: 'consumer'
    volumes:
      - './mnt/consumer:/app/config'
    networks:
      - disco-dataspace
      - consumer-network
    ports:
      - '22001:11001'
      - '22002:11002'
      - '22003:11003'
      - '22004:11004'
      - '22005:5005'
      - '23001:12001'

  consumer-ui:
    image: ghcr.io/sovity/edc-ui:4.1.8
    platform: linux/amd64
    ports:
      - '11000:8080'
      - '11015:5005'
    networks:
      - consumer-network
    environment:
      EDC_UI_ACTIVE_PROFILE: 'sovity-open-source'
      EDC_UI_CONFIG_URL: 'edc-ui-config'
      EDC_UI_MANAGEMENT_API_URL: 'http://localhost:11002/api/management'
      EDC_UI_MANAGEMENT_API_KEY: 'ApiKeyDefaultValue'
      EDC_UI_CATALOG_URLS: 'http://consumer-edc:11003/api/dsp'
      EDC_UI_MANAGEMENT_API_URL_SHOWN_IN_DASHBOARD: 'http://localhost:11002/control/api/management'
      NGINX_ACCESS_LOG: 'off'

  consumer-db:
    image: docker.io/bitnami/postgresql:15
    restart: always
    environment:
      POSTGRESQL_USERNAME: 'edc'
      POSTGRESQL_PASSWORD: 'edc'
      POSTGRESQL_DATABASE: 'edc'
    ports:
      - '54322:5432'
    volumes:
      - 'consumer-db:/bitnami/postgresql'
    networks:
      - consumer-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U edc']
      interval: 1s
      timeout: 5s
      retries: 10
