include:
  - dataspace-compose.yaml

volumes:
  provider-db:

networks:
  provider-network:

services:
  provider-edc:
    image: ghcr.io/imec-int/edc-extensions/sovity-xce:latest
    platform: linux/amd64
    depends_on:
      provider-db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      MY_EDC_PARTICIPANT_ID: 'provider'
      MY_EDC_TITLE: 'Provider EDC'
      MY_EDC_DESCRIPTION: 'Extended Sovity Community Edition EDC Connector'
      MY_EDC_CURATOR_URL: 'https://www.imec-int.com/en'
      MY_EDC_CURATOR_NAME: 'imec'
      MY_EDC_MAINTAINER_URL: 'https://www.imec-int.com/en'
      MY_EDC_MAINTAINER_NAME: 'imec'

      MY_EDC_FQDN: 'provider-edc'
      EDC_API_AUTH_KEY: ${EDC_API_AUTH_KEY}

      MY_EDC_JDBC_URL: 'jdbc:postgresql://provider-db:5432/edc'
      MY_EDC_JDBC_USER: 'edc'
      MY_EDC_JDBC_PASSWORD: ${POSTGRESQL_PASSWORD}

      WEB_HTTP_PUBLIC_PATH: '/public'
      WEB_HTTP_PUBLIC_PORT: 12001

      # docker compose local dev environment overrides (don't use with non-dev images)
      MY_EDC_PROTOCOL: 'http://'
      EDC_DATAPLANE_TOKEN_VALIDATION_ENDPOINT: 'http://provider-edc:11003/api/control/token'
      EDC_DSP_CALLBACK_ADDRESS: 'http://provider-edc:11003/api/dsp'
      EDC_WEB_REST_CORS_ENABLED: 'true'
      EDC_WEB_REST_CORS_HEADERS: 'origin,content-type,accept,authorization,X-Api-Key'
      EDC_WEB_REST_CORS_ORIGINS: '*'
      EDC_AGENT_IDENTITY_KEY: 'client_id'

      # DAPS
      EDC_OAUTH_TOKEN_URL: 'http://daps:8080/realms/DAPS/protocol/openid-connect/token'
      EDC_OAUTH_PROVIDER_AUDIENCE: 'http://localhost:8080/realms/DAPS'
      EDC_OAUTH_PROVIDER_JWKS_URL: 'http://daps:8080/realms/DAPS/protocol/openid-connect/certs'
      EDC_OAUTH_TOKEN_EXPIRATION: 15 # in minutes
      EDC_OAUTH_CLIENT_ID: 'provider'
      EDC_KEYSTORE: 'config/keystore/provider.p12'
      EDC_KEYSTORE_PASSWORD: ${EDC_PROVIDER_KEYSTORE_PASSWORD}
      EDC_OAUTH_CERTIFICATE_ALIAS: 'provider'
      EDC_OAUTH_PRIVATE_KEY_ALIAS: 'provider'
    volumes:
      - './mnt/provider:/app/config'
    networks:
      - disco-dataspace
      - provider-network
    ports:
      - '11001:11001'
      - '11002:11002'
      - '11003:11003'
      - '11004:11004'
      - '11005:5005'
      - '12001:12001'

  provider-ui:
    image: ghcr.io/sovity/edc-ui:4.1.8
    platform: linux/amd64
    ports:
      - '22000:8080'
    networks:
      - provider-network
    env_file:
      - .env
    environment:
      EDC_UI_ACTIVE_PROFILE: 'sovity-open-source'
      EDC_UI_CONFIG_URL: 'edc-ui-config'
      EDC_UI_MANAGEMENT_API_URL: 'http://localhost:22002/api/management'
      EDC_UI_MANAGEMENT_API_KEY: ${EDC_API_AUTH_KEY}
      EDC_UI_CATALOG_URLS: 'http://provider-edc:11003/api/dsp'
      NGINX_ACCESS_LOG: 'off'

  provider-db:
    image: docker.io/bitnami/postgresql:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRESQL_USERNAME: 'edc'
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_DATABASE: 'edc'
    ports:
      - '54321:5432'
    volumes:
      - 'provider-db:/bitnami/postgresql'
    networks:
      - provider-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U edc']
      interval: 1s
      timeout: 5s
      retries: 10
